### ISSUE TITLE
Uzupełnić przyciski

### ISSUE THREAD

**Issue by WojciechKuz** [di0xinho/MiASI_projekt#5]
Uzupełnić, dodać przyciski
- Ułamki
- Potęgi
- Nawiasy
- sin, cos, tg
- logarytmy
- pierwiastki
- pi, e
- abs (wart. bezwzgl.)

@di0xinho Jak wpadniesz na pomysł, co jeszcze dodać, to napisz komentarz pod tym issue

**Comment by di0xinho** [comment]
Spróbuję coś dziś albo w weekend pokombinować jeszcze

**Comment by WojciechKuz** [comment]
Napisałem funkcje do automatycznego tworzenia przycisków.
Teraz wystarczy podać listę znaków, które mają być na przyciskach.

Potrzeba jeszcze dodać przycisk backspace (skasuj znak). Przycisk skasuj historię będzie poza klawiaturą (nad listą z historią obliczeń).
Porównując do kalkulatora naukowego, brakuje u nas jeszcze funkcji cyklometrycznych (arcsin, arccos, arctan).
